# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/dummy/**/*'

Metrics/BlockLength:
  Exclude:
    - spec/**/*

LineLength:
  Exclude:
    - spec/**/*

StringLiterals:
  Enabled: false

TrailingBlankLines:
  Enabled: true