# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/dummy/**/*'
